name: 错误报告
description: 在使用过程中遇到了错误
title: '[Bug?]: '
labels: [ "bug?" ]

body:
  - type: markdown
    attributes:
      value: |
        ### 感谢您愿意填写错误报告！
        ### 以下是一些注意事项，请务必阅读使其能够更容易处理

        #### ❗| 确定没有相同问题的ISSUE已被提出.
        #### ❔| 请提供出现问题前后的完整日志内容。**请自行删除日志内存在的个人信息及敏感内容。**

        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述内容"
          required: true
        - label: "我已经在 [ISSUES](https://github.com/jinsulive/lagrange-boot/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 bug 出现？
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true

  - type: textarea
    id: reproduce-code
    attributes:
      label: 简单的复现代码/链接（可选）
      render: Java

  - type: textarea
    id: logging
    attributes:
      label: 错误日志（可选）
      render: Shell

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）